config/routes.rb
Rails.application.routes.draw do
  root 'users#home'
 
    resources :lists do
      resources :tasks do
        member do
          patch :done
        end
      end
    end

   resources :users do
     resources :lists 
   end

 

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"


  delete "/logout", to: "sessions#destroy"

  get '/auth/:provider/callback', to: 'sessions#omniauth'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    has_many :users
    has_many :tasks, :dependent => :destroy
    # accepts_nested_attributes_for :tasks

    validates :title, presence: true
    validates :description, presence: true, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed" }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  has_many :users, through: :lists
  
  validates :task, presence: true
  
  def done?
    !done.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :lists
    has_many :tasks, through: :lists

    validates :email, presence: true
    validates :email, uniqueness: true 

    def self.from_omniauth(auth)
        where(uid: auth.uid).first_or_create do |user|
            user.first_name = auth.info.first_name
            user.uid = auth.uid
            user.email = auth.info.email
            user.password = SecureRandom.hex
        end
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
    helper_method :logged_in?, :current_user, :redirect_if_not_logged_in

    def logged_in?
        #checks if session is set to user-ID i.e if user is logged in returns true if so 
        session[:user_id]
    end

    def current_user
        @user ||= User.find_by(id: session[:user_id])
    end 
   
    
    def redirect_if_not_logged_in
        if !logged_in?
          flash[:error] = "Log in to View Your Lists."
          redirect_to login_path
        end 
    end 

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    before_action :set_list, only: [:show, :edit,:update, :destroy]

    def index
      redirect_if_not_logged_in
      if params[:user_id]
          @user = User.find_by(id: params[:user_id])
            if @user.nil?
              redirect_to users_path, notice: 'user not found'
            else
              @lists = @user.lists
            end
      else
        @lists = List.all
        @user = User.find_by_id(params[:id])
      end
    end

    def show
      if params[:user_id]
        @user = User.find_by_id(params[:user_id])
        @list = current_user.lists.find_by_id(id: params[:id])
        if @list.nil?
          redirect_to user_lists_path(@user), alert: "List not found"
        end
      else
       @list = List.find(params[:id])
      end
    end

    def new
        @list = List.new
    end

    def create
      @list = List.new(list_params)
      @list.user_id = current_user.id
      if @list.save
        redirect_to user_lists_path(@user), notice: "List was successfully created"
      else
        render new_list_path
      end
    end

    def edit
      @list = List.find(params[:id])
    end

    def update
      @list = List.find(params[:id])
      @list.update(list_params)
      redirect_to @list, notice: "List was successfully updated."
    end

    def destroy
      # binding.pry
      List.find(params[:id]).destroy
      # binding.pry
      redirect_to lists_path
    end

    private

    def set_list
      @list = List.find_by_id(params[:id])
    end

    def list_params
        params.require(:list).permit(:title, :description, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    # before_action :authenticate_user!, except: :google

    def new
        # redirect_if_logged_in
        @user = User.new
    end


    def create
        @user = User.find_by(email: params[:email])
        # binding.pry
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render 'sessions/new'
        end
    end

    def destroy
        session.destroy
        redirect_to '/'
    end

    def omniauth
        # binding.pry
        @user = User.from_omniauth(auth)
        # binding.pry
        @user.save
        # binding.pry
        session[:user_id] = @user.id
        redirect_to user_path(@user)
    end
    
    private
      
    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_list
    before_action :set_task, except: [:create]
    
    def index
    end

    def create
      @task = @list.tasks.build(task_params)
      @task.save
      redirect_to @list
    end

    # def edit
    #   @task = Task.find(params[:id])
    # end
  
    # def update
    #     @task = Task.find(params[:id])
    #     @task.update(list_params)
    #     redirect_to @list
    # end

    def destroy
        @task = @list.tasks.find(params[:id])
        if @task.destroy
            flash[:success] = "Task was deleted."
        else
            flash[:error] = "Task couldn't be deleted."
        end
        redirect_to @list
    end

    def done
      @task.update_attribute(:done, Time.now)
      redirect_to @list, notice: "Task Completed"
    end

    private

    def set_list
        @list = List.find(params[:list_id])
    end
    
    def set_task
        @task = @list.tasks.find(params[:id])
    end

    def task_params
        params.require(:task).permit(:task,)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    # def index
    #     @users = User.all
    # end

    def show
        # redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          redirect_to user_path(@user)
        else
            render 'new'
        end
    end


    private
    def user_params
        params.require(:user).permit(:first_name, :username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JotAm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
  
    <div class="container">
    <%= yield %>
    <% if !logged_in? %>
       <%= link_to "Sign Up", '/signup' %> |
       <%= link_to "Log In", '/login' %> |
       <%= link_to "Log In via Google", '/auth/google_oauth2' %>
    <% else %>
      <%# <%= link_to 'My Lists', user_list(@user) %>
      <a href="/users/<%=current_user.id %>/lists">My Lists</a>
      | <%= link_to "Log Out", '/logout', method: :delete %>
    <% end %>
   </div>

  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
   <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
   </div>
   <div class="field">
        <%= f.label :description %>
        <%= f.text_field :description %>
   </div>
   <div class="actions">
        <%= f.submit %>
   </div>
<% end %>

app/views/lists/edit.html.erb
<h1 class="list_title">Edit List</h1>

<%= render 'form', list: @list %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.title %></td>
        <td><%= list.description %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create a List', new_list_path %> |

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<div id="tasks_wrapper">
 <%= render @list.tasks %>
</div>


<%= link_to 'Edit', edit_list_path(@list) %> | <%= link_to 'Delete', @list, method: :delete, data: { confirm: 'Are you sure?' } %> | <%= link_to "Create Task", new_list_task_path(@list) %> |

app/views/tasks/_form.html.erb
<%= form_for([@list, @list.tasks.build]) do |f| %>
 <%= f.text_field :task, placeholder: "New Task" %>
 <%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<div class="row clearfix">
 <% if task.done? %>
    <div class="done">
      <%= link_to "Mark as Complete", done_list_task_path(@list, task.id), method: :patch %>
    </div>
    <div class="task">
      <p style="opacity: 0.4;"><strike><%= task.task %></strike></p>
    </div>
    <div class="trash">
      <%= link_to "Delete", list_task_path(@list, task.id), method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
 <% else %>
    <div class="done">
      <%= link_to "Mark as Complete", done_list_task_path(@list, task.id), method: :patch %>
    </div>
    <div class="task">
      <p><%= task.task %></p>
    </div>
    <div class="trash">
      <%= link_to "Delete", list_task_path(@list, task.id), method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
 <% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'form', task: @task %>

app/views/users/home.html.erb
<h1>Welcome To JotAm APP</h1>
<h5>To create your first to do list:</h5>

app/views/users/index.html.erb
<ul>
<% @users.each do |user| %>
    <li><%= link_to user.first_name, user_path(user) %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
<p><%= f.label :first_name %></p>
<p><%= f.text_field :first_name%></p>
<p><%= f.label :username %></p>
<p><%= f.text_field :username%></p>
<p><%= f.label :email %></p>
<p><%= f.text_field :email%></p>
<p><%= f.label :password %></p>
<p><%= f.password_field :password %></p>
<p><%= f.label :password_confirmation %></p>
<p><%= f.password_field :password_confirmation, required: true %></p>
<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.first_name %></h1>
<% @user.lists.each do |list| %>
<p><%= link_to list.title, user_list_path(@user, list) %></p>
<% end %>



<%# <%= link_to "Log Out", '/logout', method: :delete %> 
<%= link_to "Create List", new_user_list_path(@user) %> | 